### ISSUE TITLE
Redis port does not need to be published

### ISSUE THREAD

**Issue by yogeek** [dockersamples/example-voting-app#108]
**Description**

Is there a reason to publish redis service port ?
It seems to me that publishing it in docker-stack.yml is unecessary (redis is accessed internally in the swarm by other services). 
When deploying the stack, one can see the published port and try to access it from a web browser but will have the following message which can be confusing :
```
-ERR wrong number of arguments for 'get' command
```

**Steps to reproduce the issue, if relevant:**
1. deploy the stack
2. open http://<host_ip>:<redis_published_port>

**Comment by lucj** [comment]
You'r right, redis does not need to be published as it's only used internally by the vote and worker services.

Quick note regarding your example:

Be careful, redis does not expose a http endpoint but a tcp one, if you use a redis client you will be able to connect to the redis service from the outside. Below and nxample when running the stack on play-with-docker.com:

````
$ redis-cli -h ip172-18-0-10-bahv0ckprd2000cias1g-30000.direct.labs.play-with-docker.com -p 30000
ip172-18-0-10-bahv0ckprd2000cias1g-30000.direct.labs.play-with-docker.com:30000>
````

Note: as no host port is provided in the redis service, the first one of the range (30000) is mapped to 6379.

**Comment by rcjsuen** [comment]
> You'r right, redis does not need to be published as it's only used internally by the vote and worker services.

I just ran into this problem also. So can anything be done here? When links popup at the top of PWD I think most people's instinct is to click on them. Seeing an error message might make people think their example hasn't been setup correctly.

**Comment by LucienBouletRoblin** [comment]
During the Black Hat 2018 conference, example-voting-app was used as a demo to demonstrate some security vulnerabilities of Docker (see around 26min at https://www.youtube.com/watch?v=HTM3ZrSvp6c, for more info, see https://hornecyber.com/media/2420/def-con-26-white-paper-v3.pdf)
I just checked with the docker-compose.yml, removing the 6379 port doesn't break anything as mentioned above. 
As good practice, I would change that but I did not tested all the other docker-compose and such.

**Comment by ManoMarks** [comment]
Can someone provide a PR for me? There are several compose/stack files, and a kube deployment file.
