### ISSUE TITLE
why do we have the "simple" yaml?

### ISSUE THREAD

**Issue by BretFisher** [dockersamples/example-voting-app#130]
We now have many compose files, some for (what seems like) local dev-focused docker-compose workflows, and some focused on swarm/k8s stack workflows.

I'm working on some updates to these files based on the last 1-2 years of feature enhancements but I don't understand the use case for the *simple*.yml files. These seem to be 90% of what's in the "normal" files but there's no docs or comments on why they exist. Can someone give us a backstory or info on their usage?

**Comment by ManoMarks** [comment]
For some demos you want to avoid the build tag error messages that come up
