### ISSUE TITLE
image problem.

### ISSUE THREAD

**Issue by GBmonmon** [dockersamples/example-voting-app#132]
The images you use don't exist on docker hub so the user cannot pull it down...

**Comment by ManoMarks** [comment]
Which images are you referring to? Is there a particular file that has the wrong images?

**Comment by GBmonmon** [comment]
Sorry for my ignorance. I was wrong about that.

**Comment by GBmonmon** [comment]
But I have a new issue that for worker container. It has status is CrashLoopBackOff.
It seems you need to have your Dockerfile have a Command to run.

**Comment by 3imediamaric** [comment]
> Sorry for my ignorance. I was wrong about that. Those image work just fine!

Hi, can you please write back what did you do with your images that they work now ...we are step into same Problem. We can pull down any images from docker-stack-windows-1809.yml File

**Comment by BretFisher** [comment]
@GBmonmon based on #136 and #138 can this issue be closed?
