### ISSUE TITLE
Docker Hub images are outdated, undocumented, duplicated, or don't exist.

### ISSUE THREAD

**Issue by BretFisher** [dockersamples/example-voting-app#143]
**Image Problems**

1. **Old Images**: Code has changed in this repo and images are older than the code, causing old PR fixes to have no effect if you're using the official images. One example:

    `dockersamples/examplevotingapp_worker:latest` is [two years old](https://hub.docker.com/r/dockersamples/examplevotingapp_worker/tags) but I fixed a 100% CPU issue [nearly two years ago](https://github.com/dockersamples/example-voting-app/commit/f5a84ab40fc590bf29b3b55dad821682fcf04872#diff-b61822e8357dcaff77eaaccf348d9134). Running current image will still spike CPU.

2. **Missing Images**: Images for alternate builds don't always exist. One example:

    This repo [has a java `worker`](https://github.com/dockersamples/example-voting-app/blob/master/worker/Dockerfile.j) as an alternative to the default dotnet `worker`, but [Hub has no image for that](https://hub.docker.com/r/dockersamples/examplevotingapp_worker/tags). I recommend building it as tag `java`. 

3. **Duplicate Image Repos**: Images are duplicated in different Hub repos. One example:

    `dockersamples/examplevotingapp_worker` and `dockersamples/worker` are the same app but different build dates. The former is what's used in all yaml and in README and what we've used for many years.  The latter has a new build, and I'm guessing was created by [the new Jenkinsfile](https://github.com/dockersamples/example-voting-app/blob/master/Jenkinsfile) added a year ago to help automate image builds, which is great, but that file is pushing to the wrong Hub repos and is not complete with the various tags and alt builds. Doing some quick searching it looks like no one is using the new image repos, so it would be OK to remove them and stick with the origionals.

4. **No Image Tag Docs**: To help people get the most out of these images and demo, it would be quite helpful to have a table in the README.md listing all the images, their tags, and the reason for those tags. One example:

    What is the difference between `:latest`, `:before`, and `:after`? What tags are for what OS/arch?

**Suggested Solutions**

If the Jenkinsfile is indeed the future, I think a single PR could fix all these issues by fixing the current image repo/tags and adding all the alt builds to it, along with a README update on tag options for demos.

- [ ] Fix current repo names for the 3 demo apps in Jenkinsfile
- [ ] Add alt builds of the 3 demo apps to Jenkinsfile
- [ ] Ensure all tags are covered by the pushes in Jenkinsfile
- [ ] Delete misnamed Hub repos
- [ ] Update README.md with a table of tags and uses

I'm looking for a thumbs up from maintainers that this would be the prefered resolution, and I'll get started on a PR. It looks like the Jenkinsfile will test the new builds in the PR but won't test the push commands until it's merged to master 😬

**Comment by azrdev** [comment]
Indeed it would be *very* helpful to have the source code of the applications in the repo matching what is run when you use one of the deployment files.

**Comment by justincormack** [comment]
Ok will sort out getting access to the hub org.

**Comment by justincormack** [comment]
We should probably just switch to using GitHub Actions, I suspect Jenkins may not be running here any more.

**Comment by BretFisher** [comment]
I'm all about that. How can we help? PR a GA using the Docker Hub Action?

**Comment by mikesir87** [comment]
I'm thinking this can be closed now that #263 and #271 have been merged. Thoughts @BretFisher?
