### ISSUE TITLE
Flask not being installed  when running Dockerfile

### ISSUE THREAD

**Issue by demjoejoh** [dockersamples/example-voting-app#151]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE EXAMPLE VOTING APP **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Description**

<!--
Briefly describe the problem you are having in a few paragraphs.
When running docker build . -t voting-app command execution goes fine until attempting to install Flask. 
**Steps to reproduce the issue, if relevant:**
1. navigate to vote directory 
2. execute " docker build . -t voting-app "
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@dkrn1-CentOs8 vote]# docker build . -t voting-app
Sending build context to Docker daemon  161.3kB
Step 1/7 : FROM python:2.7-alpine
2.7-alpine: Pulling from library/python
89d9c30c1d48: Pull complete 
8dfb98e486fe: Pull complete 
6e6483f96b64: Pull complete 
a0538f573931: Pull complete 
Digest: sha256:b2c105bb491b7709201d7142f425f535c93c62c4479fa0bce9ad3105f5b63fe5
Status: Downloaded newer image for python:2.7-alpine
 ---> 780ede8fb4a7
Step 2/7 : WORKDIR /app
 ---> Running in 1e8b0ea9248f
Removing intermediate container 1e8b0ea9248f
 ---> d7b2bf6590e9
Step 3/7 : ADD requirements.txt /app/requirements.txt
 ---> 6ddfe351d3ba
Step 4/7 : RUN pip install -r requirements.txt
 ---> Running in c4e0827691c6
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f04b201cd10>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/flask/**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by pprofili-contrast** [comment]
RUN pip install -r requirements.txt --trusted-host=pypi.org --trusted-host=files.pythonhosted.org

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
