### ISSUE TITLE
error when trying to reproduce the "docker-compose up"

### ISSUE THREAD

**Issue by zzygyx9119** [dockersamples/example-voting-app#153]
**Got error when trying to reproduce the "docker-compose up" **

**Output of `docker version`:**
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**output of running "docker-compose up**
```
Building worker
Step 1/5 : FROM microsoft/dotnet:2.0.0-sdk
 ---> fde8197d13f4
Step 2/5 : WORKDIR /code
 ---> Using cache
 ---> 669d92fbc80d
Step 3/5 : ADD src/Worker /code/src/Worker
 ---> Using cache
 ---> 71a36dd19109
Step 4/5 : RUN dotnet restore -v minimal src/Worker     && dotnet publish -c Release -o "./" "src/Worker/"
 ---> Running in f9dd38f5733c
MSBUILD : error MSB1050: Specify which project or solution file to use because the folder "src/Worker" contains more than one project or solution file.
ERROR: Service 'worker' failed to build: The command '/bin/sh -c dotnet restore -v minimal src/Worker     && dotnet publish -c Release -o "./" "src/Worker/"' returned a non-zero code: 1

```

**Docker for mac:**

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
