### ISSUE TITLE
error of  run docker-compose up --build

### ISSUE THREAD

**Issue by li-yizhi** [dockersamples/example-voting-app#157]
Please provide the following information so we can assess the issue you're having

**Description**

Follow instruct [Start a sample application](https://docs.docker.com/docker-for-windows/dashboard/)
error of  run docker-compose up --build.

**Steps to reproduce the issue, if relevant:**
1.Install Docker Desktop on Windows
2.Start a Redis container
3.download the Example voting app from the Docker samples page. 
4.run  docker-compose up --build

**Describe the results you received:**
ERROR: Encountered errors while bringing up the project.
**Describe the results you expected:**
the application successfully starts
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
ERROR: for result Cannot start service result: Ports are not available: listen tcp 0.0.0.0:5858: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**
Docker for Windows

**Comment by azrdev** [comment]
> listen tcp 0.0.0.0:5858: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

sounds more like a permission problem with your docker on windows, not the voting app

**Comment by mikesir87** [comment]
Closing this issue now that it's 2+ years old and we've been fixing a lot of issues. If it's still an issue, feel free to open a new issue and we'll gladly investigate. Apologies that it's taken so long to respond to you!
