### ISSUE TITLE
Using docker stack deploy not updting votes

### ISSUE THREAD

**Issue by mavrick202** [dockersamples/example-voting-app#163]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE EXAMPLE VOTING APP **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

Deployed the voting app on Docker Swarm running engine 19.03.6.

When deployed using docker stack deploy, the application is deployed well but the votes are not getting updated. When tried with docker-compose the applicaton working as expected.But with Docker Stack Deploy, the votes are not getting update.

**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by azrdev** [comment]
probably the same as #162

**Comment by rajamodu** [comment]
Try this for env for postgres db hope this voting docker stack will work.

db:
image: postgres:9.4
environment:
POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: "postgres"
volumes:
- db-data:/var/lib/postgresql/data
networks:
- backend

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
