### ISSUE TITLE
Unable to launch the application and result app in 5000,5001 port respectively. 

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [dockersamples/example-voting-app#172]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE EXAMPLE VOTING APP **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Description**
Unable to launch the application and result app in 5000,5001 port respectively. 

Followed the steps mentioned about making the app up and running. 

**Steps to reproduce the issue, if relevant:**
1.
![example_voting_app](https://user-images.githubusercontent.com/54025065/84022370-c0585800-a9a3-11ea-8477-e942bb721c1c.PNG)

2.
3.

**Describe the results you received:**
Unable to launch the voting app and result in app in GUI.

**Describe the results you expected:**
We should have been able to launch the voting app and result in app in GUI. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
19.03.8
```
(paste your output here)
```

**Output of `docker info`:**
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s
 Swarm: active
  NodeID: wcvz7i9y6helneu5wlad4yyby
  Is Manager: true
  ClusterID: nrr4ya4byznp6fsencgq482f7
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.206GiB
 Name: docker-desktop
 ID: 6JPU:SLRG:WNFH:APSU:5RKW:VIE7:4Y7P:DPNP:DC6H:LFOZ:MUQR:X7QN
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 60
  Goroutines: 167
  System Time: 2020-06-08T10:50:24.583468785Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by T-e-j-k-u-m-a-r** [comment]
Adding the snapshot of the voting app and result app

![resultapp_1](https://user-images.githubusercontent.com/54025065/84022593-2644df80-a9a4-11ea-9289-3267ad5464af.PNG)
![votingapp_1](https://user-images.githubusercontent.com/54025065/84022601-28a73980-a9a4-11ea-95c6-62bc90562ecf.PNG)

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
