### ISSUE TITLE
Worker pod is not working error code : CrashLoopBackoff

### ISSUE THREAD

**Issue by abi-save** [dockersamples/example-voting-app#173]
[**](url
![Screenshot 2020-07-18 at 3 12 03 PM](https://user-images.githubusercontent.com/65153476/87849812-30de8700-c909-11ea-9c01-96429dd2a484.png)
) PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE EXAMPLE VOTING APP **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Description**

**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

``` 19.03.12
19.03.12```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by abi-save** [comment]
[
![image](https://user-images.githubusercontent.com/65153476/87850822-b9acf100-c910-11ea-8349-88aa4b827c8b.png)
![Screenshot 2020-07-18 at 4 06 40 PM](https://user-images.githubusercontent.com/65153476/87850830-d2b5a200-c910-11ea-8efc-01418799932a.png)

](url)

**Comment by abi-save** [comment]
Work pod error log

**Comment by mustyfdn** [comment]
Hi, if you work on cloud like aws, you should open port for redis and postgres.

**Comment by hoover67** [comment]
I'm having the exact same issue on my openstack based microk8s cluster (3 nodes running on Ubuntu focal). 

I've checked the security groups and ports 3000-32xxx are allowed between nodes internally. 

Cheers, Uwe

**Comment by hoover67** [comment]
I managed to fix the issue by deleting an older "wordpress" deployment managed by helm which I'd forgotten about. :-)

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
