### ISSUE TITLE
Browser error - The page isn't working

### ISSUE THREAD

**Issue by pro100tom** [dockersamples/example-voting-app#175]
I have installed the Docker Desktop app on MacOS Catalina 10.15.5 and example-voting-app_result_1 is not displaying in the browser (tested on Chrome). Other containers work fine, including the example-voting-app_vote_1.

All the containers run well, despite the fact one of them is not displaying result in the browser, it still is running and the console window is not showing any errors.

I did restart the container multiple times and did restart the whole app too. Same result. 

I have downloaded the project by cloning it via git and ran the commands specified in the "Getting Started" tutorial.

Can one identify the problem please?

**Comment by mikesir87** [comment]
Closing this issue now that it's 2+ years old and we've been fixing a lot of issues. If it's still an issue, feel free to open a new issue and we'll gladly investigate. Apologies that it's taken so long to respond to you!
