### ISSUE TITLE
Clarify benefit of current architecture vs simpler architecture

### ISSUE THREAD

**Issue by schollii** [dockersamples/example-voting-app#188]
**Description**

It is not apparent why the redis and Worker container are needed. Seems like having the Python app directly put votes in the DB would be sufficient. Is it just to make the example a little more complex / interesting or am I missing something? The README should explain.

**Comment by BretFisher** [comment]
It's just to make the example more useful. Queues, persistent data, etc. This isn't an example of a properly architected perfectly designed distributed app... it's just a simple example of the various types of pieces and languages you might see, and how to deal with them in Docker at a basic level.

**Comment by schollii** [comment]
Can I submit a PR that puts that in the readme?

**Comment by BretFisher** [comment]
sure

**Comment by schollii** [comment]
Submitted. I hope you'll excuse my use of some of your explanation.

**Comment by mikesir87** [comment]
Closed due to merging of #191
