### ISSUE TITLE
Update the architecture graphic

### ISSUE THREAD

**Issue by BretFisher** [dockersamples/example-voting-app#196]
Update the graphic to show the various options for running a service. For example, indicate the worker is .NET or Java.

Also, since it has arrows to indicate traffic paths, maybe consider showing network boundaries and user access points.

**Comment by DivSriv** [comment]
#231 - Hi Bret, I've updated the architecture diagram with graphics and icons for respective services and to show the various options for running a service. 
Please take a look and approve/merge if its okay.

**Comment by mikesir87** [comment]
Closing as no longer relevant now that we're simplifying the repo and removing all of the other options.
