### ISSUE TITLE
ERROR: Service 'vote' failed to build: image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by hs14428** [dockersamples/example-voting-app#198]
**Description**
Hi team, 
I am pretty new to docker and devOps in general and so was trying to follow the docker dashboard tutorial for windows and I ran into the following error whe trying to setup the example voting app:

I receive the following error:
ERROR: Service 'vote' failed to build: image operating system "windows" cannot be used on this platform
when i try and run the first command from the instructions for windows:
docker-compose -f docker-compose-windows.yml build
I have git cloned the repo and I am trying to run the command in said repo.

**Steps to reproduce the issue, if relevant:**
1. git clone git@github.com:dockersamples/example-voting-app.git
2. cd example-voting-app
3. docker-compose -f docker-compose-windows.yml build

**Describe the results you received:**
ERROR: Service 'vote' failed to build: image operating system "windows" cannot be used on this platform

**Describe the results you expected:**
Succesfull command line execution so that the new commands:
docker-compose -f docker-compose-windows.yml up -d
could be run.

If you need anymore information, please let me know. As I mentioned I am new to all this (currently studying) so might be missing something obvious!

Thanks in advance,
Harry

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 6.074GiB
 Name: docker-desktop
 ID: Q4RB:5J7I:HJSM:PVVK:K522:JNX6:3DJ7:UJDD:REQU:LFHH:YXKM:DFUE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by parzival92** [comment]
Hello @hs14428 

Above issue has been resolved?

Server: Docker Engine - Community
 Engine:
  **OS/Arch:          linux/amd64**

You can use **docker-compose up** under example-voting-app .
No need to use docker-compose-windows.yml in your case.

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
