### ISSUE TITLE
Question: About replicas and parallelism.

### ISSUE THREAD

**Issue by nrikiji** [dockersamples/example-voting-app#203]
Thank you for the great samples.I would like to ask you a question.

https://github.com/dockersamples/example-voting-app/blob/e433be5d16aa4ea3aa8384c96565f4c2cafd9ddc/docker-stack.yml#L8-L12

If replicas is 1 and parallelism is 2 (or more than 2), what effect are you expecting? if replicas is 1, is it not a rolling update because there are times when containers are temporarily zero?

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
