### ISSUE TITLE
Worker pod not able to connect to db

### ISSUE THREAD

**Issue by akshaygmenon** [dockersamples/example-voting-app#215]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE EXAMPLE VOTING APP **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

The worker pod is not able to connect to the database

I am deploying this on Openshift and I was able to get the vote and result services running, but when I try to deploy the worker pod, I see that the pod is running, but on checking the logs I see continuous logging of "Waiting for db" , due to that I am not able to connect to the database and not able to see the voting in real time.

Has anyone else seen this error and have any idea on how to fix this on platform running Openshift ver 4.8?

Thanks,

AKshay

**Comment by thejordanclark** [comment]
I'm getting the same error.

**Comment by gelbander** [comment]
Try adding the following environment variable in `db-deployment.yaml`. 

```
- name: POSTGRES_HOST_AUTH_METHOD
   value: trust
```

**Comment by prabhatsingh014** [comment]
With the given yamls, worker-app uses the db credentials "postgres:postgres", so you'll need to specify two environment variables with the db (postgres) deployment i.e. POSTGRES_USER: postgres and POSTGRES_PASSWORD: postgres.
Once that's done, worker-app will automatically connect to the db.

**Comment by feriva22** [comment]
If you install postgres with minimum version 12, u must add argument for authentication encryption method to md5 , u can add this environtment variable to postgres deployment file
name: POSTGRES_INITDB_ARGS \
              value: "--auth-host=md5 --auth-local=md5"

**Comment by mluelmo** [comment]
> If you install postgres with minimum version 12, u must add argument for authentication encryption method to md5 , u can add this environtment variable to postgres deployment file name: POSTGRES_INITDB_ARGS value: "--auth-host=md5 --auth-local=md5"

I've solved worker to db connection issues after adding this env variable. Thanks @feriva22

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
