### ISSUE TITLE
ERRO[0000]: db

### ISSUE THREAD

**Issue by khandriod** [dockersamples/example-voting-app#219]
I am facing this error. the postgres:9.4 status exited. How to keep it up?

docker run --link redis:redis --link db:db  worker-app

docker: Error response from daemon: Cannot link to a non running container: /db AS /silly_volhard/db.
ERRO[0000] error waiting for container: context canceled

thanks

**Comment by prabhatsingh014** [comment]
Looks like your db container is not running which is a dependency to run worker-app container.

**Comment by BretFisher** [comment]
We're sorry for the late response. Linux images have been refreshed, cleaned up, and are now multi-platform. If you're still having issues with the latest images, feel free to reopen this ticket.
