### ISSUE TITLE
How to run this on EKS cluster ?

### ISSUE THREAD

**Issue by arnav300** [dockersamples/example-voting-app#229]
Hi,

I have EKS cluster running and I have created the deployments using K8-spec directory.
However I am unable to hit the URL of the exposed microservice.

Do I need to enable anything in my ELS cluster ?

**Comment by BretFisher** [comment]
The manifests use NodePort services. You might need to do something in EKS like a LoadBalancer service or an Ingress route. Those things are different in each cluster and K8s distribution. We only test this demo with Docker Desktop.
