### ISSUE TITLE
add aarch64/ARMv8 example stack

### ISSUE THREAD

**Issue by vielmetti** [dockersamples/example-voting-app#66]
Following the request of @alexellis in https://github.com/docker/example-voting-app/pull/64 , build an example stack for aarch64 (ARM64, ARMv8).

**Comment by vielmetti** [comment]
One component of this is the Python component, and if there was a multiarch Python it would help a lot. Cf. https://github.com/docker-library/python/issues/175

**Comment by ManoMarks** [comment]
Closing as #64 closed
