### ISSUE TITLE
Busy polling in the worker service leads to excessive CPU usage

### ISSUE THREAD

**Issue by ikisusi** [dockersamples/example-voting-app#88]
The worker service seems to busy poll Redis with `listleftpop()` in a busy loop. This results in excessive CPU usage. This may be due to fact that StackExchange.Redis (SE.Redis) does not offer matching methods for the blocking left or rights pops of the Redis (BLPOP/BLROP)? According to the [SE.redis documentation](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/PipelinesMultiplexers.md) blocking primitives will never be supported and pub/sub should be used instead. This would require subscription to be added to the worker. Since the voting service does `redis.rpush('votes', data)` without `publish`  it would need to be modified as well.

**Comment by oherrala** [comment]
To get my laptop stay cooler, I added a tactical one second sleep. This is just a workaround before real fix is carved.

```diff
diff --git a/worker/src/Worker/Program.cs b/worker/src/Worker/Program.cs
index 78ccff4..7cc6eb8 100644
--- a/worker/src/Worker/Program.cs
+++ b/worker/src/Worker/Program.cs
@@ -51,10 +51,11 @@ namespace Worker
                         }
                     }
                     else
                     {
                         keepAliveCommand.ExecuteNonQuery();
+                        Thread.Sleep(1000);
                     }
                 }
             }
             catch (Exception ex)
             {
```
