### ISSUE TITLE
ERROR: Service 'vote' failed to build: no matching manifest for windows/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by timomta** [dockersamples/example-voting-app#91]
ERROR: Service 'vote' failed to build: no matching manifest for windows/amd64 in the manifest list entries

I cloned the repository
PS C:\samples> git clone https://github.com/dockersamples/example-voting-app.git
Cloning into 'example-voting-app'...
remote: Counting objects: 377, done.
Receiving objects:  94% (355/377)   0 (delta 0), pack-reused 377
Receiving objects: 100% (377/377), 204.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (133/133), done.

Changed into the clone directory and attempted to build the sample
PS C:\samples\example-voting-app> docker-compose up
Building vote
Step 1/7 : FROM python:2.7-alpine
2.7-alpine: Pulling from library/python
ERROR: Service 'vote' failed to build: no matching manifest for windows/amd64 in the manifest list entries
PS C:\samples\example-voting-app>

I'm running on a Windows 10 dev box with the Docker for Windows client installed. It is running in Windows Container mode.

Any ideas why the sample will not come up?

**Comment by ManoMarks** [comment]
Yes, all these containers are Linux base containers. You need to switch to Linux mode.

**Comment by timomta** [comment]
Ah, got it. This comment from the Getting Started page (https://github.com/dockersamples/example-voting-app/ on the Readme.md) confused me:
"Download Docker. If you are on Mac or Windows, Docker Compose will be automatically installed. On Linux, make sure you have the latest version of Compose."

I mistakenly took that to mean that this sample was designed to work with any of the platforms.

Is it possible to note at the start of that readme that this is a Linux sample - you can run it on the Windows platform by switching to Linux containers? Might be clearer for new folks to understand.

Thanks for your response!

**Comment by ManoMarks** [comment]
Warning added in #96
