### ISSUE TITLE
vote and result services not starting

### ISSUE THREAD

**Issue by Jeffboq** [dockersamples/example-voting-app#97]
**Description**
When starting application with `docker-compose up -d`, both _vote_ and _result_ services do not work.

**Steps to reproduce the issue, if relevant:**
1. ``docker-compose up -d``
2. `docker-compose ps`

**Describe the results you received:**
```
$ docker-compose ps
             Name                            Command               State             Ports
---------------------------------------------------------------------------------------------------
db                                docker-entrypoint.sh postgres    Up       5432/tcp
examplevotingappmaster_result_1   nodemon server.js                Exit 0
examplevotingappmaster_vote_1     python app.py                    Exit 2
examplevotingappmaster_worker_1   /bin/sh -c dotnet src/Work ...   Up
redis                             docker-entrypoint.sh redis ...   Up       0.0.0.0:32770->6379/tcp
```

**Describe the results you expected:**
_examplevotingappmaster_result_1_ and _examplevotingappmaster_vote_1_ containers should be in **up** state.

**Additional information you deem important (e.g. issue happens only occasionally):**
Here is the result of `docker-compose logs` command (db & redis services omitted for clarity) 
```
Attaching to examplevotingappmaster_worker_1, db, examplevotingappmaster_result_1, redis, examplevotingappmaster_vote_1
worker_1  | Waiting for db
worker_1  | Connected to db
worker_1  | Connecting to redis
worker_1  | Found redis at 172.19.0.2
vote_1    | python: can't open file 'app.py': [Errno 2] No such file or directory
result_1  |   Usage: nodemon [nodemon options] [script.js] [args]
result_1  |
result_1  |   See "nodemon --help" for more.
result_1  |
result_1  |   Usage: nodemon [nodemon options] [script.js] [args]
```
**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:39:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**
Running Docker Toolbox on Windows 8.1

**Comment by yigitbasalma** [comment]
Hi All;

I resolved that issue.I couldn't understand why we have experienced this issue but my solution worked. =) My docker-compose.yml is below.You could use them if you want.

`version: "2"

services:
  vote:
    build: ./vote
    #volumes:
    # - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    #volumes:
    #  - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:`

**Comment by yigitbasalma** [comment]
I found the cause of the issue.My docker and docker-compose version too old.I'm upgraded following the steps of the site below and it worked.

https://docs.docker.com/engine/installation/linux/docker-ce/fedora/
